//! Runtime execution tests for compiled Paideia fixtures.
//!
//! This harness:
//! 1. Compiles a .pdx fixture to a .o object file
//! 2. Synthesizes a C driver that poisons CPU registers
//! 3. Links driver.c + fixture.o with gcc
//! 4. Runs the binary and verifies the exit code

mod common;

mod runtime {
    pub mod harness;
    pub mod driver_template;

    mod option_result;
    mod flat_lambda_binop_canaries;
    mod flat_lambda_binop_mul_var_var_value;
    mod flat_lambda_binop_div_var_var_value;
    mod flat_lambda_binop_mod_var_var_value;
    mod flat_lambda_binop_div_var_var_rdx_live_value;
    mod match_enum_pattern;
    mod match_nested_pattern;
    mod ms_call_saves_rcx_value;
    mod four_arg_call_saves_rcx_value;
    mod two_let_with_tail_binop_value;
    mod single_let_then_tail_add_value;
    mod let_with_binop_rhs_value;
    mod let_with_bitnot_rhs_value;
    mod let_with_bitnot_shl_rhs_value;
    mod let_chain_2_of_2_value;
    mod let_chain_3_of_3_value;
    mod let_chain_2_typed_value;
    mod let_chain_2_binop_value;
    mod let_chain_2_call_value;
    mod let_chain_2_match_value;
    mod func_scope_enum_let_a_value;
    mod func_scope_enum_let_b_value;
    mod func_scope_enum_let_c_value;
    mod func_scope_multiple_lets_value;
    mod func_scope_enum_let_shadow_value;
    mod payload_let_payload_c_value;
    mod payload_let_payload_a_value;
    mod payload_let_b_pass_thru_value;
    mod payload_let_mixed_value;
    mod bare_enum_cons_lambda_value;
    mod app_rhs_enum_pair_ok_value;
    mod pair_binding_call_preserve_value;
    mod binop_arg1_scratch_respects_pattern_binder_value;
    mod caller_var_pair_arg_value;
    mod caller_app_pair_arg_value;
    mod caller_literal_pair_arg_value;
    mod match_wildcard_last_value;
    mod nested_match_two_lets_unit_value;
    mod nested_match_two_lets_payload_value;
    mod nested_match_three_deep_value;
    mod nested_match_same_var_value;
    mod block_match_direct_expr_value;
    mod block_match_braced_2arm_value;
    mod block_match_braced_3arm_value;
    mod block_match_braced_nested_value;
    mod sysv_bridge_bump_value;
    mod let_rhs_binop_mul_value;
    mod two_payload_lets_arith_value;
    mod two_payload_lets_separate_matches_value;
    mod nested_match_two_lets_payload_arith_value;
    mod let_rhs_binop_div_value;
    mod let_rhs_binop_mod_value;
    mod module_var_assign_mul_value;
    mod module_var_assign_div_value;
    mod module_var_assign_mod_value;
    mod pick3_arm_a_value;
    mod pick3_arm_b_value;
    mod pick3_arm_c_value;
    mod pick4_arm_a_value;
    mod pick4_arm_b_value;
    mod pick4_arm_c_value;
    mod pick4_arm_d_value;
    mod pick4uv_arm_a_value;
    mod pick4uv_arm_b_value;
    mod pick4uv_arm_c_value;
    mod pick4uv_arm_d_value;
    mod pick5_arm_c_value;
    mod pick5_arm_e_value;
    mod pick5uv_arm_c_value;
    mod pick8uv_arm_e_value;
    mod intmatch_lit_zero_value;
    mod intmatch_lit_one_value;
    mod intmatch_lit_three_value;
    mod intmatch_lit_falls_through_value;
    mod intmatch_default_value;
    mod intmatch_var_local_let_value;
    mod intmatch_var_param_value;
    mod intmatch_var_i32_value;
    mod enum_qual_arg_pos0_3arg_value;
    mod enum_qual_arg_pos0_3arg_b_value;
    mod enum_qual_arg_pos0_4arg_value;
    mod enum_qual_arg_pos0_2arg_value;
    mod enum_qual_arg_pos1_2arg_value;
    mod enum_qual_arg_mixed_locals_value;
    mod enum_match_arm_binop_mul_value;
    mod fn_param_enum_scrutinee_value;
    mod unit_var_module_let_matches_value;
    mod unit_var_module_let_matches_b_value;
    mod unit_var_module_let_matches_c_value;
    mod unit_var_multiple_bindings_value;
    mod cmp_lt_true_value;
    mod cmp_lt_false_value;
    mod cmp_gt_true_value;
    mod cmp_le_eq_true_value;
    mod cmp_ge_eq_true_value;
    mod cmp_eq_true_value;
    mod cmp_ne_true_value;
    mod guard_int_true_takes_arm_value;
    mod guard_int_false_falls_through_value;
    mod guard_two_arms_first_fails_value;
    mod guard_enum_payload_binder_value;
    mod guard_enum_wildcard_default_guarded_value;
    mod guard_pattern_binder_not_leaked_value;
    mod guard_wildcard_true_matches_value;
    mod or_pat_int_first_value;
    mod or_pat_int_second_value;
    mod or_pat_int_falls_through_value;
    mod or_pat_int_three_alts_value;
    mod or_pat_enum_unit_first_value;
    mod or_pat_enum_unit_second_value;
    mod or_pat_enum_payload_ok_value;
    mod or_pat_int_with_guard_value;
    mod bind_int_literal_value;
    mod bind_int_falls_through_value;
    mod bind_or_pattern_value;
    mod bind_with_guard_value;
    mod bind_with_guard_false_value;
    mod bind_variant_unit_value;
    mod command_dispatch_shell;
}
