[package]
name = "paideia-as-stdlib"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
paideia-as-emitter-pe = { path = "../paideia-as-emitter-pe", optional = true }

[dev-dependencies]
regex = { workspace = true }

[features]
regen-uefi-template = ["paideia-as-emitter-pe"]
