[package]
name = "paideia-as-emit"
version = "0.16.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"
authors = ["Santiago Núñez-Corrales <snunezcr@gmail.com>"]
repository = "https://github.com/paideia-os/paideia-as"
homepage = "https://paideia-os.org"
publish = false

[dependencies]
paideia-as-encoder = { path = "../paideia-as-encoder" }
paideia-as-runtime = { path = "../paideia-as-runtime" }

[dev-dependencies]
iced-x86 = { workspace = true }
smallvec = { workspace = true }
insta = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
